import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Shared Components/Navbar";
import { Inter, Oswald } from "next/font/google";
import ExerciseContextProvider from "@/Context/ExerciseContext";
import { ToastContainer } from "react-toastify";
import Footer from "./Components/Shared Components/Footer";
// import "react-toastify/dist/ReactToastify.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const oswald = Oswald({
  subsets: ["latin"],
  variable: "--font-oswald",
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body
        className={`${inter.className} ${oswald.className} min-h-full flex flex-col bg-black`}
      >
        <ExerciseContextProvider>
          <Navbar></Navbar>
          {children}
          <ToastContainer />
        </ExerciseContextProvider>
      </body>
      <Footer></Footer>
    </html>
  );
}
